# Generated by Django 3.2 on 2021-04-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_inclusion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
