# Generated by Django 3.2 on 2021-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_date_inclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_inclusion',
            field=models.DateField(),
        ),
    ]
